### PR TITLE
Update to HiddenMarkovModels v0.6

### PR DESCRIPTION
**Pull request by gdalle**
I recently released a breaking version of HiddenMarkovModels, so here's a small PR updating the compat bound and adding a few `view`s in passing for speed

### CODE REVIEW

**Comment by dmetivie** [comment]
Thanks! I just up version and added your new `AbstractVectorOrNTuple` type for `seq_ends`.

**Review by dmetivie — APPROVED** [review]

**Comment by gdalle** [comment]
> Thanks! I just up version and added your new AbstractVectorOrNTuple type for seq_ends.

This is not documented so it is not part of the public API and could break in patch release. At the moment you should not rely on this functionality.

**Comment by gdalle** [comment]
The main reason I introduced it was to activate or deactivate multithreading based on dispatch, so that a single sequence (passed as `seq_ends=(T,)`) would not trigger the overhead of multithreading. It is mostly an internal change.

**Comment by dmetivie** [comment]
Do you recommend removing the type annotation for `seq_ends` in `StatsAPI.fit!` function, then?
Keeping the old `AbstractVector{Int}` was making the code error.

**Comment by gdalle** [comment]
I would recommend simply removing the annotation on `seq_ends` in your custom `fit!`, since now it must be able to accept both a vector and a tuple. I believe that's how I do it in the new docs but I'll gladly take suggestions to document this a bit better.

**Comment by gdalle** [comment]
And lastly, you don't need to release a breaking version when you update a dependency like that, except when it has an impact on your package's own user-facing API. So here tagging v0.2.1 would probably have sufficed. But we can discuss it face to face in Toulouse ;)

**Comment by dmetivie** [comment]
Dam! I can always revert the pkg number since it not release yet? 

Can't wait (I'll be there only Tuesday, unfortunately)!

**Pull request merged**
